# Site settings
title: vincent /things
email: gnux123@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gnux123.github.io" # the base hostname & protocol for your site
twitter_username: vincent.sue
github_username:  vincent.sue

# Build settings
markdown: kramdown
