url: https://gnux123.github.io
baseurl: 

# Site settings
title: vincent's Things
email: gnux123@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
contests:
- name: Coscup年會(2010-2012)
  pic: coscup
  des: 從2010年到2013年每屆的coscup都有參加。

- name: webconf年會(2013)
  pic: webconf
  des: 透過webConf活動，增進及了解最新前端技術。

- name: Yahoo!Open Hack(2012-2013)
  pic: yahooHack
  des: 從2012年到2013年連續參加兩年的yahoo open hack day，透過這樣的比賽可以讓自己的技術更加磨練。

- name: HPX每月大聚及小講座
  pic: hpx
  des: 透過參與這些大小講座累積相關UI/UX資訊，並將這些資訊轉化並應用在相關工作上面。

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://tw.linkedin.com/pub/vincent-su/73/861/587/en
  - title: envelope
    url: gnux123@gmail.com
  - title: pinterest
    url: https://www.pinterest.com/gnux123/
  - title: bitbucket 
    url: http://bitbucket.org/gnux123
  - title: github
    url: http://github.com/gnux123
# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
